version: '3.4'

services:
  mongodbwdocker2:
    image: jnilssonn/910039c7cde9:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:8080"
    networks:
      - mynetwork

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
    networks:
      - mynetwork
  
  
  react:
    image: jnilssonn/reactapp1:latest
    volumes:
     - ./src:/app/src
    ports:
     - 3000:3000
    stdin_open: true
    environment:
     - CHOKIDAR_USEPOLLING=true
    command: npm start
    networks:
     - mynetwork

networks:
  mynetwork:
    driver: bridge
